'use client';
import {useEffect,useMemo,useState} from 'react';
export default function DashboardV2(){
 const [show,setShow]=useState(false),[rows,setRows]=useState([]),[rep,setRep]=useState('');
 const load=()=>fetch('/api/surveys',{cache:'no-store'}).then(r=>r.json()).then(d=>setRows(Array.isArray(d)?d:[])).catch(()=>setRows([]));
 useEffect(()=>{const check=()=>setShow(!!document.querySelector('.tabs button:nth-child(3).on'));check();document.addEventListener('click',()=>setTimeout(check,0));load()},[]);
 const reps=useMemo(()=>[...new Set(rows.map(x=>x.sales_rep).filter(Boolean))].sort(),[rows]);
 const data=rep?rows.filter(x=>x.sales_rep===rep):rows;
 const csv=()=>{const cols=['dentist_name','region','district','van_company','current_pms','sales_rep','contract_end_date'];const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const text='\ufeff'+[cols,...data.map(x=>cols.map(k=>x[k]))].map(r=>r.map(q).join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='VAN_설문_'+(rep||'전체')+'.csv';a.click();URL.revokeObjectURL(u)};
 if(!show)return null;
 return <section style={{width:'min(1180px,calc(100vw - 30px))',margin:'-760px auto 40px',position:'relative',zIndex:5,background:'#fff',minHeight:760,padding:20,boxSizing:'border-box',fontFamily:'Arial,Malgun Gothic,sans-serif'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h2 style={{margin:0}}>VAN 설문 대시보드</h2><small>V2 전용 DB 실시간 연동</small></div><div style={{display:'flex',gap:8}}><select value={rep} onChange={e=>setRep(e.target.value)}><option value="">전체 영업사원</option>{reps.map(x=><option key={x}>{x}</option>)}</select><button onClick={csv}>엑셀 내려받기</button><a href="/admin">Admin</a></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10,margin:'18px 0'}}>{[['총 조사',data.length],['영업사원',reps.length],['지역',new Set(data.map(x=>x.region)).size],['약정정보',data.filter(x=>x.contract_end_date).length]].map(([k,v])=><div key={k} style={{border:'1px solid #ddd',borderRadius:10,padding:16}}><small>{k}</small><b style={{display:'block',fontSize:28}}>{v}</b></div>)}</div><h3>공략 리스트</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['치과명','지역','VAN','PMS','영업사원','약정만료'].map(x=><th key={x} style={{padding:8,background:'#f3f3f3'}}>{x}</th>)}</tr></thead><tbody>{data.map(r=><tr key={r.id}><td>{r.dentist_name}</td><td>{r.region} {r.district}</td><td>{r.van_company}</td><td>{r.current_pms}</td><td>{r.sales_rep}</td><td>{r.contract_end_date}</td></tr>)}</tbody></table></div></section>
}
