'use client';
import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import AdminV2 from './AdminV2';
const n=v=>Number(String(v||'').replace(/[^0-9.-]/g,''))||0;
const a=v=>Array.isArray(v)?v:[];
const diff=ym=>{const m=/^(\d{4})-(\d{2})/.exec(ym||'');if(!m)return 999;const d=new Date();return(Number(m[1])-d.getFullYear())*12+Number(m[2])-d.getMonth()-1};
export default function DashboardV2(){const[mount,setMount]=useState(null),[rows,setRows]=useState([]),[rep,setRep]=useState('');
 const load=async()=>{const r=await fetch('/api/surveys',{cache:'no-store'});if(r.ok)setRows(await r.json())};
 useEffect(()=>{let node;const find=()=>{const old=document.querySelector('.tab3');if(old&&!node){old.style.display='none';node=document.createElement('div');old.after(node);setMount(node);load()}};find();const o=new MutationObserver(find);o.observe(document.body,{childList:true,subtree:true});return()=>{o.disconnect();node?.remove()}},[]);
 const reps=useMemo(()=>[...new Set(rows.map(x=>x.sales_rep).filter(Boolean))].sort((x,y)=>x.localeCompare(y,'ko')),[rows]);const data=rep?rows.filter(x=>x.sales_rep===rep):rows;
 const regions=Object.entries(data.reduce((o,x)=>(o[x.region]=(o[x.region]||0)+1,o),{})).sort((x,y)=>y[1]-x[1]);const exp=k=>data.filter(x=>{const d=diff(x.contract_end_date);return d>=0&&d<=k}).length;
 const csv=()=>{const H=['치과명','지역','구군','VAN','PMS','영업사원','약정만료','월사용료','관리비','연동비','불편사항','개선항목'],B=data.map(x=>[x.dentist_name,x.region,x.district,x.van_company,x.current_pms,x.sales_rep,x.contract_end_date,x.monthly_cost,x.management_fee,x.link_fee,a(x.inconveniences).join('|'),a(x.improvement_items).join('|')]),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',blob=new Blob(['\ufeff'+[H,...B].map(r=>r.map(q).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`VAN_상담대상_${rep||'전체'}.csv`;link.click();URL.revokeObjectURL(link.href)};
 if(!mount)return null;const S={card:{background:'#fff',border:'1px solid #e6e6e6',borderRadius:12,padding:16},btn:{border:'1px solid #ddd',background:'#fff',borderRadius:8,padding:'9px 13px',fontWeight:700,cursor:'pointer'},td:{padding:'8px',borderBottom:'1px solid #eee',fontSize:12}};
 return createPortal(<div className="dashboard-v2" style={{width:'min(1180px,calc(100vw - 28px))',margin:'20px auto 40px',fontFamily:'Arial,"Malgun Gothic",sans-serif'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end'}}><div><h1 style={{margin:0}}>VAN 설문 대시보드</h1><p style={{color:'#777'}}>설문 현황과 약정 만료 영업기회를 한 화면에서 확인합니다.</p></div><button style={S.btn} onClick={load}>새로고침</button></div><div style={{display:'flex',gap:8,justifyContent:'flex-end',margin:'10px 0'}}><select style={S.btn} value={rep} onChange={e=>setRep(e.target.value)}><option value="">전체 영업사원</option>{reps.map(x=><option key={x}>{x}</option>)}</select><button style={S.btn} onClick={csv}>↓ 엑셀 내려받기</button><AdminV2 onChanged={load}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:10}}>{[['총 조사',data.length],['불편 경험',data.filter(x=>a(x.inconveniences).length).length],['개선 희망',data.filter(x=>a(x.improvement_items).length).length],['3개월내 만료',exp(3)],['12개월내 만료',exp(12)]].map(([l,v])=><div style={S.card} key={l}><small>{l}</small><b style={{display:'block',fontSize:28}}>{v}</b></div>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1.3fr',gap:12,marginTop:12}}><section style={S.card}><h3>지역별 조사 현황</h3>{regions.map(([r,c])=><div key={r} style={{display:'flex',gap:8,margin:'7px 0'}}><b style={{width:45}}>{r}</b><span style={{flex:1,background:'#eee',height:9,marginTop:5,borderRadius:8}}><i style={{display:'block',background:'#f36f21',height:'100%',width:`${c/Math.max(1,...regions.map(x=>x[1]))*100}%`,borderRadius:8}}/></span><span>{c}</span></div>)}</section><section style={S.card}><h3>약정 만료 파이프라인</h3><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}>{[[3,exp(3)],[6,exp(6)],[12,exp(12)]].map(([m,v])=><div key={m} style={{background:'#fff5ee',padding:20,textAlign:'center',borderRadius:10}}><b style={{fontSize:30,color:'#f36f21'}}>{v}</b><small style={{display:'block'}}>{m}개월 이내</small></div>)}</div></section></div><section style={{...S.card,marginTop:12}}><h3>공략 리스트</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['치과명','지역','VAN','PMS','영업사원','약정만료','월비용','불편/개선'].map(h=><th style={{...S.td,background:'#f5f5f5'}} key={h}>{h}</th>)}</tr></thead><tbody>{[...data].sort((x,y)=>(x.contract_end_date||'9999').localeCompare(y.contract_end_date||'9999')).map(r=><tr key={r.id}><td style={S.td}><b>{r.dentist_name}</b></td><td style={S.td}>{r.region} {r.district}</td><td style={S.td}>{r.van_company}</td><td style={S.td}>{r.current_pms}</td><td style={S.td}>{r.sales_rep}</td><td style={S.td}>{r.contract_end_date||'-'}</td><td style={S.td}>{(n(r.monthly_cost)+n(r.management_fee)+n(r.link_fee)).toLocaleString()}원</td><td style={S.td}>{[...a(r.inconveniences),...a(r.improvement_items)].slice(0,3).join(', ')}</td></tr>)}</tbody></table></div></section></div>,mount)}
