'use client';
import {useMemo,useState} from 'react';
const n=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0;
const fmt=v=>n(v).toLocaleString('ko-KR');
function Num({value,onChange,suffix='원'}){return <span><input className="money" inputMode="numeric" value={value} onChange={e=>onChange(n(e.target.value))}/>{suffix}</span>}
function Choice({value,onChange,items}){return <div className="checks">{items.map(x=><label className="pill" key={x}><input type="radio" checked={value===x} onChange={()=>onChange(x)}/>{x}</label>)}</div>}
export default function Page(){
 const [clinic,setClinic]=useState(''); const [region,setRegion]=useState(''); const [contact,setContact]=useState(''); const [sales,setSales]=useState('');
 const [devices,setDevices]=useState({terminal:{use:true,type:'임대',rent:10000,manage:10000,pms:15000},multi:{use:true,type:'번들',rent:0,manage:0,pms:0},sign:{use:false,type:'구입',rent:0,manage:0,pms:0},etc:{use:false,type:'임대',rent:0,manage:0,pms:0}});
 const upd=(k,f,v)=>setDevices(s=>({...s,[k]:{...s[k],[f]:v}}));
 const [paperType,setPaperType]=useState('유상'); const [paperYear,setPaperYear]=useState(30000);
 const [support,setSupport]=useState({inquiry:'불편',repair:'불편',visit:'없음'});
 const [contract,setContract]=useState({van:'NICE',agency:'OO사',term:'3년',expiry:'0000년00월',cancel:'기기대금 3배',usage:'100건/월'});
 const calc=useMemo(()=>{let gear=0,manage=0,pms=0,etc=0; Object.entries(devices).forEach(([k,d])=>{if(!d.use)return; if(k==='etc')etc=(n(d.rent)+n(d.manage)+n(d.pms))*36; else {gear+=n(d.rent)*36;manage+=n(d.manage)*36;pms+=n(d.pms)*36}}); return {gear,manage,pms,etc,subtotal:gear+manage+pms+etc}},[devices]);
 const [manual,setManual]=useState({}); const val=(k,auto)=>manual[k]??auto; const setM=(k,v)=>setManual(s=>({...s,[k]:v}));
 const currentSubtotal=val('subtotal',calc.subtotal||1260000), osSubtotal=val('osSubtotal',360000); const currentPaper=val('paper',paperYear*3||90000), osPaper=val('osPaper',0); const currentTotal=val('total',currentSubtotal+currentPaper),osTotal=val('osTotal',osSubtotal+osPaper);
 const devNames={terminal:'단말기',multi:'멀티패드',sign:'서명패드',etc:'기타'};
 return <main className="wrap"><section className="hero"><h1>카드결제서비스(VAN) 설문</h1><p>“카드결제 사용중 불편한 점을 확인해서 도와드리고자 합니다.” · 아는 항목만 체크하셔도 됩니다. · 약 3분 소요</p></section>
 <div className="grid"><section className="card full"><div className="title">기본정보</div><div className="grid"><div className="row"><b>치과명</b><input value={clinic} onChange={e=>setClinic(e.target.value)}/></div><div className="row"><b>지역</b><input value={region} onChange={e=>setRegion(e.target.value)}/></div><div className="row"><b>연락처</b><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="성함/전화번호"/></div><div className="row"><b>오스템 영업사원</b><input value={sales} onChange={e=>setSales(e.target.value)}/></div></div></section>
 <section className="card full"><div className="title"><span className="sectionNo">1</span>결제 기기 사용 현황 (복수선택)</div><div className="devices">{Object.entries(devices).map(([k,d])=><div className="device" key={k}><h3><input style={{width:'auto'}} type="checkbox" checked={d.use} onChange={e=>upd(k,'use',e.target.checked)}/> {devNames[k]}</h3><select value={d.type} onChange={e=>upd(k,'type',e.target.value)}><option>구입</option><option>임대</option><option>번들</option></select><div className="row"><span>할부금/임대료</span><Num value={d.rent} onChange={v=>upd(k,'rent',v)} suffix="원/월"/></div><div className="row"><span>관리비</span><Num value={d.manage} onChange={v=>upd(k,'manage',v)} suffix="원/월"/></div><div className="row"><span>PMS연동비</span><Num value={d.pms} onChange={v=>upd(k,'pms',v)} suffix="원/월"/></div></div>)}</div></section>
 <section className="card"><div className="title"><span className="sectionNo">2</span>소모품 사용 현황</div><div className="row"><b>용지 형태</b><Choice value={paperType} onChange={setPaperType} items={['무상','유상']}/></div><div className="row"><b>용지 비용</b><Num value={paperYear} onChange={setPaperYear} suffix="원/년"/></div></section>
 <section className="card"><div className="title"><span className="sectionNo">3</span>고객 대응 현황</div><div className="row"><b>문의 응대</b><Choice value={support.inquiry} onChange={v=>setSupport(s=>({...s,inquiry:v}))} items={['원할','불편']}/></div><div className="row"><b>고장 수리</b><Choice value={support.repair} onChange={v=>setSupport(s=>({...s,repair:v}))} items={['원할','불편']}/></div><div className="row"><b>방문 점검</b><Choice value={support.visit} onChange={v=>setSupport(s=>({...s,visit:v}))} items={['수시','없음']}/></div></section>
 <section className="card full"><div className="title"><span className="sectionNo">4</span>계약 조건 점검</div><div className="grid">{[['VAN사','van'],['대리점','agency'],['약정기간','term'],['약정만료','expiry'],['중도해지시','cancel'],['매월 이용건수','usage']].map(([lab,k])=><div className="row" key={k}><b>{lab}</b><input value={contract[k]} onChange={e=>setContract(s=>({...s,[k]:e.target.value}))}/></div>)}</div></section>
 <section className="card full"><div className="title">“오스템 VAN서비스와 비교해 드립니다”</div><p className="note">앞 설문 답변을 선택하면 자동으로 채워지며, 모든 표 값은 직접 수정할 수 있습니다.</p><h3>기본비용 비교</h3><table><thead><tr><th>항목</th><th>현재</th><th>오스템</th><th>비고</th></tr></thead><tbody>{[['기기','gear',calc.gear||360000,252000,''],['관리','manage',calc.manage||360000,108000,''],['연동','pms',calc.pms||540000,0,'원클릭 이용시'],['기타','etc',calc.etc,0,'']].map(([lab,k,a,o,note])=><tr key={k}><td>{lab}</td><td><Num value={val(k,a)} onChange={v=>setM(k,v)} suffix="원/3년"/></td><td><Num value={val('os'+k,o)} onChange={v=>setM('os'+k,v)} suffix="원/3년"/></td><td>{note}</td></tr>)}<tr><th>소계</th><th><Num value={currentSubtotal} onChange={v=>setM('subtotal',v)} suffix="원/3년"/></th><th><Num value={osSubtotal} onChange={v=>setM('osSubtotal',v)} suffix="원/3년"/></th><th></th></tr><tr><th>차이</th><th className="diff" colSpan="2">{fmt(currentSubtotal-osSubtotal)}원/3년</th><th>현재 - 오스템</th></tr></tbody></table>
 <h3>소모품 비용 비교</h3><table><thead><tr><th>항목</th><th>현재</th><th>오스템</th><th>비고</th></tr></thead><tbody><tr><td>용지</td><td><Num value={currentPaper} onChange={v=>setM('paper',v)} suffix="원/3년"/></td><td><Num value={osPaper} onChange={v=>setM('osPaper',v)} suffix="원/3년"/></td><td>정상 이용시</td></tr><tr><th>차이</th><th className="diff" colSpan="2">{fmt(currentPaper-osPaper)}원/3년</th><th>현재 - 오스템</th></tr></tbody></table>
 <h3>고객 대응 비교</h3><table><thead><tr><th>항목</th><th>현재</th><th>오스템</th><th>비고</th></tr></thead><tbody><tr><td>문의 응대</td><td><input value={support.inquiry} onChange={e=>setSupport(s=>({...s,inquiry:e.target.value}))}/></td><td><input defaultValue="더 원할(전문성)"/></td><td></td></tr><tr><td>고장 수리</td><td><input value={support.repair} onChange={e=>setSupport(s=>({...s,repair:e.target.value}))}/></td><td><input defaultValue="더 원할(전문성)"/></td><td></td></tr><tr><td>방문 점검</td><td><input value={support.visit} onChange={e=>setSupport(s=>({...s,visit:e.target.value}))}/></td><td><input defaultValue="수시(영업사원)"/></td><td>국내최대영업망</td></tr></tbody></table>
 <h3>계약 조건 비교</h3><table><thead><tr><th>항목</th><th>현재</th><th>오스템</th><th>비고</th></tr></thead><tbody>{[['VAN사','van','K'],['대리점','agency','오스템'],['약정','term','3년'],['만료','expiry','-'],['해지','cancel','할부잔금'],['이용','usage','40건/월']].map(([lab,k,o])=><tr key={k}><td>{lab}</td><td><input value={contract[k]} onChange={e=>setContract(s=>({...s,[k]:e.target.value}))}/></td><td><input defaultValue={o}/></td><td></td></tr>)}<tr><th>총비용</th><th><Num value={currentTotal} onChange={v=>setM('total',v)} suffix="원/3년"/></th><th><Num value={osTotal} onChange={v=>setM('osTotal',v)} suffix="원/3년"/></th><th>기본비용 소계 + 소모품</th></tr></tbody></table><div className="actions"><button className="btn" type="button">설문 저장 (DB 연결 예정)</button></div></section></div></main>}
