'use client';
import {useEffect,useMemo,useState} from 'react';
import Dashboard from './Dashboard';
import SurveyTab from './SurveyTab';
import {freshSurvey,normalizeSurvey,restoreLocalDraft,calculateComparison} from './survey-costs';
import './survey-tab.css';

const number=v=>Number(String(v??'').replace(/[^0-9.-]/g,''))||0;
const fmt=v=>number(v).toLocaleString('ko-KR');
const fresh=freshSurvey;
export function Money({value,onChange,label,unit='원/3년'}){return <span className="money"><input aria-label={label} value={value===''?'':fmt(value)} inputMode="numeric" onChange={e=>onChange(e.target.value===''?'':Math.max(0,number(e.target.value)))}/><small>{unit}</small></span>}
function Comparison({s,c,change,proposal=false}){
 const override=(k,v)=>change({...s,overrides:{...s.overrides,[k]:v}});
 const cell=(key,value,unit='원/3년')=><Money label={(proposal?'제안 ':'비교 ')+key+' 비용'} value={value} onChange={v=>override(key,v)} unit={unit}/>;
 const text=(key)=><input aria-label={(proposal?'제안 ':'비교 ')+key} value={s.contract[key]} onChange={e=>change({...s,contract:{...s.contract,[key]:e.target.value}})}/>;
 const groups=[{title:'기본비용 비교',key:'basic',saving:c.currentBase+c.etc-c.osBase-c.osEtc,body:<><table><thead><tr><th colSpan="2">항목</th><th>현재</th><th className="os-head">오스템</th><th>비고</th></tr></thead><tbody><tr><td rowSpan="3" className="row-group">단말<br/>세트</td><td>소계</td><td>{cell('currentBase',c.currentBase)}</td><td className="os-cell">{cell('osBase',c.osBase)}</td><td className="note">단말+멀티패드</td></tr>{[['기기','gear','osGear'],['관리','manage','osManage']].map(([name,key,os])=><tr key={key}><td>{name}</td><td>{cell(key,c[key])}</td><td className="os-cell">{cell(os,c[os])}</td><td className="note">{key==='pms'?'원클릭 이용시':''}</td></tr>)}<tr><td colSpan="2">기타</td><td>{cell('etc',c.etc)}</td><td className="os-cell">{cell('osEtc',c.osEtc)}</td><td/></tr></tbody></table></>},
 {title:'부대 비용 비교',key:'paper',saving:c.ancillary-c.osAncillary,body:<table><thead><tr><th>항목</th><th>현재</th><th className="os-head">오스템</th><th>비고</th></tr></thead><tbody><tr><td>용지</td><td>{cell('paper',c.paper)}</td><td className="os-cell">{cell('osPaper',c.osPaper)}</td><td className="note">정상 이용시</td></tr><tr><td>PMS연동</td><td>{cell('pms',c.pms)}</td><td className="os-cell">{cell('osPms',c.osPms)}</td><td className="note">원클릭 연동시</td></tr></tbody></table>},
 {title:'고객 대응 비교',key:'support',body:<table><thead><tr><th>항목</th><th>현재</th><th className="os-head">오스템</th><th>비고</th></tr></thead><tbody>{[['문의 응대','inquiry','더 원활(전문성)',''],['고장 수리','repair','더 원활(전문성)',''],['방문 점검','visit','수시(영업사원)','국내 최대 영업망']].map(([title,key,os,note])=><tr key={key}><td>{title}</td><td><input aria-label={'비교 '+title} value={s.support[key]} onChange={e=>change({...s,support:{...s.support,[key]:e.target.value}})}/></td><td className="os-cell">{os}</td><td className="note">{note}</td></tr>)}</tbody></table>},
 {title:'계약 조건 비교',key:'contract',body:<table><thead><tr><th colSpan="2">항목</th><th>현재</th><th className="os-head">오스템</th><th>비고</th></tr></thead><tbody>{(proposal?[['약정','term','3년'],['만료','expiry','-']]:[['VAN사','van','K'],['대리점','agency','오스템'],['약정','term','3년'],['만료','expiry','-']]).map(([title,key,os],i,items)=><tr key={key}>{i===0&&<td rowSpan={items.length+1} className="row-group">기본<br/>정보</td>}<td>{title}</td><td>{text(key)}</td><td className="os-cell">{os}</td><td/></tr>)}<tr><td>총비용</td><td>{cell('total',c.total)}</td><td className="os-cell">{fmt(c.osTotal)}<small>원/3년</small></td><td/></tr><tr><td rowSpan="2" className="row-group">위약금</td><td>해지</td><td>{text('cancel')}</td><td className="os-cell">할부잔금</td><td/></tr><tr><td>이용</td><td>{text('usage')}</td><td className="os-cell">40건/월</td><td/></tr></tbody></table>}];
 return <div className={proposal?'proposal-comparisons':'survey-comparisons'}>{groups.map(g=><div className={'compare-group '+g.key} key={g.key}>{proposal&&<aside><h3>{g.title}</h3><div className="saving-box">{g.saving!==undefined?<><span>{g.saving>=0?'절감':'증가'}</span><b>{fmt(Math.abs(g.saving))}</b><small>원/3년</small></>:<span>기존 &lt; 오스템</span>}</div></aside>}<section className="comparison">{!proposal&&<h3>{g.title}</h3>}{g.body}{!proposal&&g.saving!==undefined&&<div className="difference">차이 <b>{fmt(g.saving)}</b> 원/3년</div>}</section></div>)}</div>
}
function Proposal({s,c,change}){const benefits=[['▣','사용성','동일한 사용 환경,\n더 편리한 서비스','기존 업무','단말기(유선)\n멀티패드\n일상업무','기존과 동일한','동일하게 제공\n(PMS 무관)'],['◎','운영비용','같은 서비스,\n더 합리적인 비용',fmt(c.total)+'원/3년','현재 사용',fmt(c.osTotal)+'원/3년','오스템'],['◇','사용조건','불필요한 부담은 줄이고,\n안정적인 운영','기기값·위약금','계약 부담','안전한 조건','기간 3년(동일),\n합리적 위약금'],['♧','지원','언제든, 더 가까이\n도와드리는 지원체계','현금 등 불법지원','준법 확인 필요','운영비용 절감','오스템 플랫폼\n서비스 경험']];return <div className="paper-sheet proposal-sheet"><div className="sheet-label">비교 제안</div><Brand/><header className="proposal-title"><h1>“오스템 <em>VAN서비스</em>와 비교해 드립니다”</h1><p>앞 설문 답변을 선택하면 자동으로 채워지며, 내용은 직접 수정할 수 있습니다.</p></header><div className="proposal-frame"><Comparison s={s} c={c} change={change} proposal/><section className="bts"><h2><em>BTS</em> 핵심 전환 제안</h2><p>익숙한 사용 방식을 그대로, 비용과 계약 위험은 가볍게</p><div className="benefits">{benefits.map(([icon,title,desc,left,ld,right,rd])=><article key={title}><header><i>{icon}</i><div><h3>{title}</h3><p>{desc}</p></div></header><div className="before-after"><div><strong>{left}</strong><small>{ld}</small></div><b>➜</b><div><strong>{right}</strong><small>{rd}</small></div></div>{title==='운영비용'&&<b className="card-saving">{c.saving>=0?'약 '+fmt(c.saving/10000)+'만원 절감':'비용 재확인 필요'}</b>}</article>)}</div><div className="saving-banner"><span>♢ <b>운영비용만으로도 저렴</b><small>+ 오스템 풀서비스 경험</small></span><strong>{c.saving>=0?'약 '+fmt(Math.round(c.saving/10000))+'만원 절감':'약 '+fmt(Math.round(-c.saving/10000))+'만원 증가'}</strong></div><div className="talking-points">{[['1','변경 부담 최소','기존 결제 경험은 그대로,\n추가 학습 없이 쉽게 전환','새로운 결제방식을 배우는 것이 아니라, 단말기 교체로 기존 흐름을 유지하면서 오스템 편의를 더하는 제안입니다.'],['2','PMS 연동 편의','수납·정산 수작업을 줄여\n업무 효율을 높입니다.','직원이 금액을 다시 입력하고 나중에 정산을 맞추는 번거로움을 줄이는 것이 핵심입니다.'],['3','현장 밀착 지원','오스템 전국 영업망과\n전담 인력이 직접 함께합니다.','결제만 파는 서비스가 아니라, 오스템 담당자가 방문해 함께 챙기는 운영관리 서비스입니다.']].map(([n,title,desc,talk])=><article key={n}><header><b>{n}</b><div><h3>{title}</h3><p>{desc}</p></div></header><div className="talk"><b>☏ 권장 멘트</b><p>“{talk}”</p></div></article>)}</div></section></div></div>}
function Brand(){return <div className="brand" aria-label="OSSTEM">OSSTEM<span>◦</span></div>}
export default function Page(){const[tab,setTab]=useState(1),[s,setS]=useState(fresh),[ready,setReady]=useState(false),[status,setStatus]=useState(''),[saving,setSaving]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('osstem-survey-v2-draft'));if(saved?.devices?.terminal&&saved?.contract)setS(restoreLocalDraft(saved));}catch{}setReady(true)},[]);
 useEffect(()=>{const root=document.querySelector('.workspace');if(!root)return;const measure=()=>document.documentElement.style.setProperty('--sheet-zoom',String(Math.min(1,root.clientWidth/1140)));measure();const observer=new ResizeObserver(measure);observer.observe(root);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('osstem-survey-v2-draft',JSON.stringify(s))}catch{}},[s,ready]);
 const change=next=>{setS(next);setStatus('')};
 const c=useMemo(()=>calculateComparison(s),[s]);
 async function submit(){if(!s.clinic.trim()||!s.region){setStatus('치과명과 지역을 입력해 주세요.');return}setSaving(true);setStatus('');try{const res=await fetch('/api/surveys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({draft:s,comparison:c})});const result=await res.json();if(!res.ok)throw Error(result.error||'저장 실패');setStatus('설문이 저장되었습니다. 대시보드에 반영했습니다.');setRevision(v=>v+1)}catch(e){setStatus(e.message||'저장하지 못했습니다. 다시 시도해 주세요.')}finally{setSaving(false)}}
 const field=(key,value)=>change({...s,[key]:value});
 return <main className="app"><nav className="tabs" aria-label="주요 메뉴">{['설문 입력','비교 제안','대시보드'].map((name,i)=><button key={name} role="tab" aria-selected={tab===i+1} className={tab===i+1?'active':''} onClick={()=>setTab(i+1)}><small>0{i+1}</small>{name}</button>)}</nav><div className="workspace"><div className="sheet-stage">{tab===1?<><SurveyTab s={s} change={change}/><section className="form-actions"><div><label><input type="checkbox" checked={s.immediate} onChange={e=>field('immediate',e.target.checked)}/>즉시 비교안 희망</label><label><input type="checkbox" checked={s.compliance} onChange={e=>field('compliance',e.target.checked)}/>준법 확인 필요</label></div><div><button onClick={()=>{if(confirm('현재 입력을 초기화할까요?')){setS(fresh());setStatus('')}}}>입력 초기화</button><button onClick={()=>setTab(2)}>비교 제안 보기</button><button className="primary" onClick={submit} disabled={saving}>{saving?'저장 중…':'설문 저장'}</button></div><p role="status">{status||'입력 내용은 이 브라우저에 임시 보관됩니다. 설문 저장을 누르면 대시보드에 등록됩니다.'}</p></section></>:tab===2?<><Proposal s={s} c={c} change={change}/><div className="print-actions"><button onClick={()=>setTab(1)}>← 설문으로</button><button className="primary" onClick={()=>window.print()}>비교 제안 인쇄 / PDF</button></div></>:<Dashboard revision={revision} onSelect={row=>{let draft=row.survey_details?.draft;if(draft?.devices){setS(normalizeSurvey(draft));setTab(2)}else{const d=fresh();d.clinic=row.dentist_name;d.region=row.region;d.district=row.district;d.sales=row.sales_rep;d.contract={...d.contract,van:row.van_company||'',agency:row.current_van_dealer||'',expiry:row.contract_end_date||'',term:row.terminal_use_period||''};d.devices.terminal={use:true,type:'임대',rent:number(row.monthly_cost),manage:number(row.management_fee),pms:number(row.link_fee)};setS(d);setTab(2)}}}/>}</div></div></main>
}
