import assert from 'node:assert/strict';
import {freshSurvey,normalizeSurvey,restoreLocalDraft,calculateComparison,updateDevice,updatePms,proposalDeviceCost} from './survey-costs.js';
const initial=freshSurvey();
const previousDraft=freshSurvey();delete previousDraft.costDefaultsVersion;previousDraft.devices.terminal.manage=10000;previousDraft.clinic='기존 입력 치과';previousDraft.overrides={manage:360000,currentBase:720000,total:1290000,osPaper:0};
const restored=restoreLocalDraft(previousDraft),restoredCosts=calculateComparison(restored);
assert.equal(restored.devices.terminal.manage,5000);assert.equal(restored.clinic,previousDraft.clinic);assert.equal(restored.overrides.osPaper,0);
assert.equal(restoredCosts.manage,180000);assert.equal(restoredCosts.currentBase,540000);assert.equal(restoredCosts.total,1110000);assert.equal(restoredCosts.saving,750000);
assert.equal(normalizeSurvey(previousDraft).devices.terminal.manage,10000);
assert.equal(restoreLocalDraft({...restored,devices:{...restored.devices,terminal:{...restored.devices.terminal,manage:10000}}}).devices.terminal.manage,10000);
assert.equal(restoreLocalDraft({...previousDraft,devices:{...previousDraft.devices,terminal:{...previousDraft.devices.terminal,manage:8000}}}).devices.terminal.manage,8000);
const costs=calculateComparison(initial);
assert.equal(costs.currentBase,540000);assert.equal(costs.osBase,360000);
assert.equal(costs.paper,30000);assert.equal(costs.pms,540000);assert.equal(costs.ancillary,570000);
assert.equal(costs.total,1110000);assert.equal(costs.saving,750000);
const noPms=calculateComparison(updatePms(initial,''));
assert.equal(noPms.currentBase,costs.currentBase);assert.equal(noPms.ancillary,30000);assert.equal(noPms.total,570000);
const legacyPms=freshSurvey();legacyPms.devices.etc={use:true,type:'임대',rent:1000,manage:500,pms:2000};
assert.equal(calculateComparison(legacyPms).etc,54000);assert.equal(calculateComparison(legacyPms).pms,612000);
assert.equal(calculateComparison(updatePms(legacyPms,0)).pms,0);
for(const kind of ['multi','sign']){assert.equal(initial.devices[kind].use,false);assert.equal(initial.devices[kind].type,'');assert.equal(proposalDeviceCost(initial,kind),'');}
let s=updateDevice(initial,'multi','use',true);
assert.equal(s.devices.multi.type,'번들');assert.equal(s.devices.sign.use,false);assert.equal(s.devices.sign.type,'');
s=updateDevice(s,'multi','rent',1000);
assert.equal(s.devices.multi.type,'임대');assert.equal(proposalDeviceCost(s,'multi','rent','month'),2500);assert.equal(proposalDeviceCost(s,'multi'),90000);
s=updateDevice(s,'multi','type','구입');assert.equal(s.devices.multi.rent,36000);
s=updateDevice(s,'sign','use',true);
assert.equal(s.devices.sign.type,'번들');assert.equal(s.devices.multi.use,false);assert.equal(s.devices.multi.type,'');assert.equal(s.devices.multi.rent,'');assert.equal(proposalDeviceCost(s,'multi'),'');
s=updateDevice(s,'sign','type','구입');s=updateDevice(s,'sign','rent',50000);
assert.equal(s.devices.sign.type,'구입');assert.equal(proposalDeviceCost(s,'sign','rent','month'),1670);assert.equal(proposalDeviceCost(s,'sign'),60000);
assert.equal(calculateComparison(s).gear,360000+50000);assert.equal(calculateComparison(s).osGear,252000+60000);
s=updateDevice(s,'multi','rent',2000);
assert.equal(s.devices.multi.use,true);assert.equal(s.devices.multi.type,'임대');assert.equal(s.devices.sign.use,false);assert.equal(s.devices.sign.type,'');assert.equal(proposalDeviceCost(s,'sign'),'');
assert.equal(calculateComparison(s).osGear,252000+90000);
s=updateDevice(s,'multi','use',false);assert.equal(s.devices.multi.type,'');assert.equal(s.devices.multi.rent,'');
s=updateDevice(s,'sign','type','번들');assert.equal(s.devices.sign.use,true);assert.equal(s.devices.multi.type,'');
const legacy=freshSurvey();legacy.devices.multi={use:true,type:'임대',rent:1000};legacy.devices.sign={use:true,type:'임대',rent:2000};
const migrated=normalizeSurvey(legacy);assert.equal(migrated.devices.multi.use,true);assert.equal(migrated.devices.sign.use,false);assert.equal(migrated.devices.sign.type,'');
const oldEmpty=freshSurvey();oldEmpty.devices.multi.type='번들';oldEmpty.devices.sign.type='번들';
assert.equal(normalizeSurvey(oldEmpty).devices.multi.type,'');assert.equal(normalizeSurvey(oldEmpty).devices.sign.type,'');
console.log('PASS: 패드 상호 배타 선택, 선택한 쪽만 기본 번들, 단일 계약 형태, 가격/합산, 기존 임시저장 정리');
