'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {amount,deviceNames,PAD_PRICES,proposalDeviceCost,updateDevice,calculateComparison} from './survey-costs';

const fmt=v=>amount(v).toLocaleString('ko-KR',{maximumFractionDigits:2});
function Money({value,onChange,label,unit}){return <label className="t1-money"><input aria-label={label} value={value===''||value==null?'':fmt(value)} inputMode="decimal" onChange={e=>onChange(e.target.value===''?'':Math.max(0,amount(e.target.value)))}/><small>{unit}</small></label>}
function Choices({value,onChange,items,label}){return <div className="t1-choices" role="radiogroup" aria-label={label}>{items.map(item=><label key={item}>{item}<input type="radio" name={label} checked={item===value} onChange={()=>onChange(item)}/></label>)}</div>}
function Title({n,children}){return <h2 className="t1-section-title"><b>{n}</b>{children}</h2>}
function DevicePicture({kind,d,update}){return <label className="t1-picture"><b>{deviceNames[kind]}</b>{kind==='etc'?<input aria-label="기타 기기 품목" placeholder="품목" value={d.name} onChange={e=>update('name',e.target.value)}/>:<Image src={`/devices/${kind}.jpg`} width={78} height={65} alt=""/>}<input type="checkbox" aria-label={`${deviceNames[kind]} 사용`} checked={d.use} onChange={e=>update('use',e.target.checked)}/></label>}
function CostPair({kind,d,field,update}){
 const value=d[field],purchase=field==='rent'&&d.type==='구입';
 const month=value===''||value==null?'':purchase?amount(value)/36:amount(value);
 const total=value===''||value==null?'':purchase?amount(value):amount(value)*36;
 const title=`${deviceNames[kind]} ${field==='rent'?'기기 비용':field==='manage'?'관리비':'PMS 연동비'}`;
 return <div className="t1-cost-pair"><Money label={`${title} 월`} value={month} onChange={v=>update(field,v===''?'':purchase?v*36:v)} unit="원/월"/><Money label={`${title} 3년`} value={total} onChange={v=>update(field,v===''?'':purchase?v:v/36)} unit="원/3년"/></div>;
}
function Saving({value,label}){return <div className="t1-savings" aria-label={label}><span>{value<0?'증가':'절감'}</span><output>{fmt(Math.abs(value))}</output><small>원/3년</small></div>}
function Advantage(){return <div className="t1-advantage">오스템이<br/>유리</div>}
export default function SurveyTab({s,change}){
 const proposal=s.proposal||{};
 const comparison=calculateComparison(s);
 const setProposal=(key,value)=>change({...s,proposal:{...proposal,[key]:value},overrides:{}});
 const setContract=(key,value)=>change({...s,contract:{...s.contract,[key]:value}});
 const [expiry,setExpiry]=useState('');
 useEffect(()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit'}).formatToParts(new Date());const year=Number(parts.find(p=>p.type==='year').value)+3,month=parts.find(p=>p.type==='month').value;setExpiry(`${year}-${month}`)},[]);
 const proposalText=(key,fallback)=>proposal[key]??fallback;
 const osPair=(kind,key='rent')=><div className="t1-cost-pair">{['month','total'].map(period=><Money key={period} label={`오스템 ${deviceNames[kind]} ${key==='rent'?'기기 비용':key==='manage'?'관리비':'PMS 연동비'} ${period==='month'?'월':'3년'}`} value={proposalDeviceCost(s,kind,key,period)} unit={period==='month'?'원/월':'원/3년'} onChange={v=>{const updates={...proposal,[`${kind}_${key}_${period}`]:v};if(v!==''&&!(PAD_PRICES[kind]&&key==='rent'))updates[`${kind}_${key}_${period==='month'?'total':'month'}`]=period==='month'?v*36:v/36;change({...s,proposal:updates,overrides:{}})}}/>)}</div>;
 const unknown=(key,label,option='모름')=><label className="t1-flag">{option}<input type="checkbox" aria-label={`${label} ${option}`} checked={s.contract[key]===option} onChange={e=>setContract(key,e.target.checked?option:'')}/></label>;
 const contractInput=(key,label,flags=['모름'])=><div className="t1-contract-field"><span>{label}</span><div className="t1-field-options"><input aria-label={label} value={flags.includes(s.contract[key])?'':s.contract[key]} onChange={e=>setContract(key,e.target.value)}/>{flags.map(flag=><span key={flag}>{unknown(key,label,flag)}</span>)}</div></div>;
 const osText=(key,label,fallback,type='text')=><label className="t1-contract-field"><span>{label}</span><input type={type} aria-label={`오스템 ${label}`} value={proposalText(key,fallback)} onChange={e=>setProposal(key,e.target.value)}/></label>;
 const field=(key,value)=>change({...s,[key]:value});
 return <div className="paper-sheet t1-sheet">
  <div className="brand" aria-label="OSSTEM">OSSTEM<span>◦</span></div>
  <header className="t1-title"><h1><Image src="/osstem-symbol.png" alt="오스템임플란트 로고" width={38} height={38} priority/> 카드결제서비스<small>(VAN)</small> 설문</h1><b>“카드결제 사용중 불편한 점을 확인해서 도와드리고자 합니다.”</b><p>아는 항목만 체크하셔도 됩니다.</p><span className="t1-minutes">약 3분 소요</span></header>
  <header className="t1-compare-title"><h2>“오스템 <em>VAN서비스</em>와 비교해 드립니다”</h2><p>앞 설문 답변을 선택하면 자동으로 채워지며, 내용은 직접 수정할 수 있습니다.</p></header>
  <section className="t1-card t1-equipment"><Title n="1">결제 기기 사용 현황 <small>(복수선택)</small></Title><div className="t1-device-grid t1-device-head"><span/><b>형태</b><b>할부금/임대료</b><b>관리비</b><b>PMS연동비</b></div>{Object.entries(s.devices).map(([kind,d])=>{const update=(k,v)=>change(updateDevice(s,kind,k,v));return <div className="t1-device-grid t1-device-row" key={kind}><DevicePicture kind={kind} d={d} update={update}/><Choices label={`${deviceNames[kind]} 계약 형태`} items={kind==='terminal'?['구입','임대']:['구입','임대','번들']} value={PAD_PRICES[kind]&&!d.use?'':d.type} onChange={v=>update('type',v)}/><CostPair kind={kind} d={d} field="rent" update={update}/>{['terminal','etc'].includes(kind)&&['manage','pms'].map(key=><CostPair key={key} kind={kind} d={d} field={key} update={update}/>)}</div>})}</section>
  <section className="t1-card t1-proposal t1-equipment-proposal"><h3><b className="t1-proposal-number">1</b>결제기기 사용 비용 제안</h3>{Object.keys(s.devices).map(kind=><div className="t1-os-device-row" key={kind}>{osPair(kind)}{['terminal','etc'].includes(kind)&&['manage','pms'].map(key=><div key={key}>{osPair(kind,key)}</div>)}</div>)}<Advantage/><Saving label="결제기기 3년 절감액" value={comparison.currentBase+comparison.etc-comparison.osBase-comparison.osEtc}/></section>
  <section className="t1-card t1-paper"><Title n="2">소모품 사용 현황</Title><div className="t1-paper-head"><span/><b>형태</b><b>비용</b></div><div className="t1-paper-row"><label className="t1-picture"><b>용지</b><Image src="/devices/paper.jpg" width={70} height={64} alt=""/><input type="checkbox" aria-label="용지 사용" checked={s.paperUse} onChange={e=>change({...s,paperUse:e.target.checked,overrides:{}})}/></label><Choices label="용지 비용 형태" items={['무상','유상']} value={s.paperType} onChange={v=>change({...s,paperType:v,overrides:{}})}/><div className="t1-cost-pair"><Money label="연간 용지 비용" value={s.paperYear} unit="원/년" onChange={v=>change({...s,paperYear:v,overrides:{}})}/><Money label="3년 용지 비용" value={s.paperYear===''?'':amount(s.paperYear)*3} unit="원/3년" onChange={v=>change({...s,paperYear:v===''?'':v/3,overrides:{}})}/></div></div></section>
  <section className="t1-card t1-proposal t1-paper-proposal"><h3><b className="t1-proposal-number">2</b>소모품 비용 제안</h3><div className="t1-cost-pair"><Money label="오스템 용지 비용 연간" value={proposal.paper_total===''?'':amount(proposal.paper_total)/3} unit="원/년" onChange={v=>setProposal('paper_total',v===''?'':v*3)}/><Money label="오스템 용지 비용 3년" value={proposal.paper_total??0} unit="원/3년" onChange={v=>setProposal('paper_total',v)}/></div><Advantage/><Saving label="소모품 3년 절감액" value={comparison.paper-comparison.osPaper}/></section>
  <section className="t1-card t1-support"><Title n="3">고객 대응 현황</Title><div className="t1-support-head">형태</div>{[['문의 응대','inquiry',['원활','불편']],['고장수리','repair',['원활','불편']],['방문점검','visit',['수시','없음']]].map(([label,key,items])=><div className="t1-support-row" key={key}><div className="t1-picture"><b>{label}</b><Image src={`/devices/${key}.jpg`} width={70} height={62} alt=""/></div><Choices label={`${label} 현황`} items={items} value={s.support[key]} onChange={v=>change({...s,support:{...s.support,[key]:v}})}/></div>)}</section>
  <section className="t1-card t1-proposal t1-support-proposal"><h3><b className="t1-proposal-number">3</b>고객 대응 제안</h3>{[['inquiry','원활 (전문성 발휘)'],['repair','원활 (전문성 발휘)'],['visit','수시 (국내최대 영업사원)']].map(([key,value])=><div className="t1-os-support-row" key={key}><input aria-label={`오스템 ${key==='inquiry'?'문의 응대':key==='repair'?'고장수리':'방문점검'}`} value={proposalText(key,value)} onChange={e=>setProposal(key,e.target.value)}/></div>)}<Advantage/></section>
  <section className="t1-card t1-contract"><Title n="4">계약 조건 점검</Title><div className="t1-contract-grid"><span className="t1-contract-group">기본정보</span>{contractInput('van','VAN사')}{contractInput('agency','대리점')}<span/>{contractInput('term','약정기간')}<div className="t1-contract-field"><span>약정만료</span><div className="t1-field-options"><input aria-label="약정만료" type="month" value={s.contract.expiry} onChange={e=>change({...s,contract:{...s.contract,expiry:e.target.value,expiryUnknown:false,expired:false}})}/><label className="t1-flag">모름<input type="checkbox" aria-label="약정만료 모름" checked={!!s.contract.expiryUnknown} onChange={e=>change({...s,contract:{...s.contract,expiryUnknown:e.target.checked,...(e.target.checked?{expiry:'',expired:false}:{})}})}/></label><label className="t1-flag">지남<input type="checkbox" aria-label="약정만료 지남" checked={!!s.contract.expired} onChange={e=>change({...s,contract:{...s.contract,expired:e.target.checked,expiryUnknown:false}})}/></label></div></div><span className="t1-contract-group t1-penalty">위약금</span>{contractInput('cancel','중도해지위약금',['모름','없음'])}{contractInput('usage','의무사용건수/월',['모름','없음'])}</div></section>
  <section className="t1-card t1-proposal t1-contract-proposal"><h3><b className="t1-proposal-number">4</b>계약 조건 제안</h3><div className="t1-os-contract-grid">{osText('van','VAN사','OOO')}{osText('agency','대리점','오스템')}{osText('term','약정기간','3년')}{osText('expiry','약정만료',expiry,'month')}{osText('cancel','중도해지위약금','할부잔금')}{osText('usage','의무사용건수/월','40건/월')}</div><Advantage/></section>
  <footer className="t1-footer"><label>치과명<input aria-label="치과명" value={s.clinic} onChange={e=>field('clinic',e.target.value)}/></label><label>지역<select aria-label="지역" value={s.region} onChange={e=>field('region',e.target.value)}><option value="">선택</option>{['서울','경기','인천','강원','충북','충남','세종','대전','전북','전남','광주','경북','대구','경남','울산','부산','제주'].map(region=><option key={region}>{region}</option>)}</select><input aria-label="구군" placeholder="구·군" value={s.district} onChange={e=>field('district',e.target.value)}/></label><label>연락처(성함/전화번호)<input aria-label="연락처" value={s.contact} onChange={e=>field('contact',e.target.value)}/></label><label>오스템 영업사원<input aria-label="오스템 영업사원" value={s.sales} onChange={e=>field('sales',e.target.value)}/></label></footer>
 </div>;
}
