import assert from 'node:assert/strict';
import {freshSurvey,normalizeSurvey,calculateComparison,updateDevice,proposalDeviceCost} from './survey-costs.js';
const initial=freshSurvey();
assert.equal(initial.devices.multi.type,'번들');assert.equal(initial.devices.sign.type,'번들');
assert.equal(initial.devices.multi.rent,'');assert.equal(initial.devices.sign.rent,'');
assert.equal(proposalDeviceCost(initial,'multi'),'');assert.equal(proposalDeviceCost(initial,'sign'),'');
assert.equal(calculateComparison(initial).osGear,252000);
let s=updateDevice(initial,'multi','rent',1000);
assert.equal(s.devices.multi.type,'임대');assert.equal(s.devices.multi.use,true);
assert.equal(proposalDeviceCost(s,'multi','rent','month'),2500);assert.equal(proposalDeviceCost(s,'multi'),90000);
s=updateDevice(s,'multi','type','구입');assert.equal(s.devices.multi.rent,36000);
s=updateDevice(s,'multi','type','임대');assert.equal(s.devices.multi.rent,1000);
s=updateDevice(s,'sign','type','구입');s=updateDevice(s,'sign','rent',50000);
assert.equal(s.devices.sign.type,'구입');assert.equal(proposalDeviceCost(s,'sign','rent','month'),1670);assert.equal(proposalDeviceCost(s,'sign'),60000);
assert.equal(calculateComparison(s).gear,360000+36000+50000);
assert.equal(calculateComparison(s).osGear,252000+90000+60000);
assert.equal(calculateComparison(s).osBase,252000+90000+60000+108000);
s=updateDevice(s,'multi','type','번들');assert.equal(s.devices.multi.rent,'');assert.equal(proposalDeviceCost(s,'multi'),'');
s=updateDevice(s,'sign','rent','');assert.equal(proposalDeviceCost(s,'sign'),'');
assert.equal(calculateComparison(s).osGear,252000);
const legacy=freshSurvey();legacy.devices.multi.type='';legacy.devices.sign.type='';
assert.equal(normalizeSurvey(legacy).devices.multi.type,'번들');
s=updateDevice(initial,'sign','rent',0);assert.equal(proposalDeviceCost(s,'sign'),60000);
s.devices.sign.use=false;assert.equal(proposalDeviceCost(s,'sign'),'');
console.log('PASS: 기본 번들, 개별 입력, 구입/임대, 제안 금액, 합산, 초기화, 기존 임시저장');
