import assert from 'node:assert/strict';
import {freshSurvey,normalizeSurvey,calculateComparison,updateDevice,proposalDeviceCost} from './survey-costs.js';
const initial=freshSurvey();
for(const kind of ['multi','sign']){assert.equal(initial.devices[kind].use,false);assert.equal(initial.devices[kind].type,'');assert.equal(proposalDeviceCost(initial,kind),'');}
let s=updateDevice(initial,'multi','use',true);
assert.equal(s.devices.multi.type,'번들');assert.equal(s.devices.sign.use,false);assert.equal(s.devices.sign.type,'');
s=updateDevice(s,'multi','rent',1000);
assert.equal(s.devices.multi.type,'임대');assert.equal(proposalDeviceCost(s,'multi','rent','month'),2500);assert.equal(proposalDeviceCost(s,'multi'),90000);
s=updateDevice(s,'multi','type','구입');assert.equal(s.devices.multi.rent,36000);
s=updateDevice(s,'sign','use',true);
assert.equal(s.devices.sign.type,'번들');assert.equal(s.devices.multi.use,false);assert.equal(s.devices.multi.type,'');assert.equal(s.devices.multi.rent,'');assert.equal(proposalDeviceCost(s,'multi'),'');
s=updateDevice(s,'sign','type','구입');s=updateDevice(s,'sign','rent',50000);
assert.equal(s.devices.sign.type,'구입');assert.equal(proposalDeviceCost(s,'sign','rent','month'),1670);assert.equal(proposalDeviceCost(s,'sign'),60000);
assert.equal(calculateComparison(s).gear,360000+50000);assert.equal(calculateComparison(s).osGear,252000+60000);
s=updateDevice(s,'multi','rent',2000);
assert.equal(s.devices.multi.use,true);assert.equal(s.devices.multi.type,'임대');assert.equal(s.devices.sign.use,false);assert.equal(s.devices.sign.type,'');assert.equal(proposalDeviceCost(s,'sign'),'');
assert.equal(calculateComparison(s).osGear,252000+90000);
s=updateDevice(s,'multi','use',false);assert.equal(s.devices.multi.type,'');assert.equal(s.devices.multi.rent,'');
s=updateDevice(s,'sign','type','번들');assert.equal(s.devices.sign.use,true);assert.equal(s.devices.multi.type,'');
const legacy=freshSurvey();legacy.devices.multi={use:true,type:'임대',rent:1000};legacy.devices.sign={use:true,type:'임대',rent:2000};
const migrated=normalizeSurvey(legacy);assert.equal(migrated.devices.multi.use,true);assert.equal(migrated.devices.sign.use,false);assert.equal(migrated.devices.sign.type,'');
const oldEmpty=freshSurvey();oldEmpty.devices.multi.type='번들';oldEmpty.devices.sign.type='번들';
assert.equal(normalizeSurvey(oldEmpty).devices.multi.type,'');assert.equal(normalizeSurvey(oldEmpty).devices.sign.type,'');
console.log('PASS: 패드 상호 배타 선택, 선택한 쪽만 기본 번들, 단일 계약 형태, 가격/합산, 기존 임시저장 정리');
